In [1]:
import sqlite3

conn = sqlite3.connect("helpdesk.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS tickets(
    ticket_id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_name TEXT,
    department TEXT,
    issue_type TEXT,
    issue_description TEXT,
    priority TEXT,
    status TEXT,
    created_date TEXT
)
""")

conn.commit()
conn.close()

print("Ticket Database Created Successfully")

Ticket Database Created Successfully

Creating Ticket

In [2]:
import sqlite3

conn = sqlite3.connect("helpdesk.db")
cursor = conn.cursor()

cursor.execute("""
INSERT INTO tickets
(employee_name, department, issue_type, issue_description, priority, status, created_date)
VALUES
(
'Eric Rathod',
'IT',
'Login Issue',
'Unable to login to Outlook account',
'High',
'Open',
'2026-06-04'
)
""")

conn.commit()
conn.close()

print("Ticket Created Successfully")

Ticket Created Successfully

View Tickets

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("helpdesk.db")

df = pd.read_sql_query("SELECT * FROM tickets", conn)

conn.close()

df

,ticket_id,employee_name,department,issue_type,issue_description,priority,status,created_date
0,1,Eric Rathod,IT,Login Issue,Unable to login to Outlook account,High,Open,2026-06-04

Adding  Multiple Sample Tickets

In [4]:
import sqlite3

conn = sqlite3.connect("helpdesk.db")
cursor = conn.cursor()

tickets = [
    ("Sara Khan","Finance","Printer Issue","Printer not responding","Medium","Open","2026-06-04"),
    ("John Smith","IT","VPN Access","Unable to connect VPN","High","In Progress","2026-06-04"),
    ("Amit Patel","HR","Password Reset","Forgot account password","Low","Closed","2026-06-04"),
    ("Priya Sharma","Operations","Software Installation","Need MS Visio installed","Medium","Open","2026-06-04")
]

cursor.executemany("""
INSERT INTO tickets
(employee_name, department, issue_type, issue_description, priority, status, created_date)
VALUES (?, ?, ?, ?, ?, ?, ?)
""", tickets)

conn.commit()
conn.close()

print("Sample Tickets Added Successfully")

Sample Tickets Added Successfully

View All Tickets

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("helpdesk.db")

df = pd.read_sql_query(
    "SELECT * FROM tickets",
    conn
)

conn.close()

df

,ticket_id,employee_name,department,issue_type,issue_description,priority,status,created_date
0,1,Eric Rathod,IT,Login Issue,Unable to login to Outlook account,High,Open,2026-06-04
1,2,Sara Khan,Finance,Printer Issue,Printer not responding,Medium,Open,2026-06-04
2,3,John Smith,IT,VPN Access,Unable to connect VPN,High,In Progress,2026-06-04
3,4,Amit Patel,HR,Password Reset,Forgot account password,Low,Closed,2026-06-04
4,5,Priya Sharma,Operations,Software Installation,Need MS Visio installed,Medium,Open,2026-06-04

Searching ticket

In [6]:
import sqlite3
import pandas as pd

employee = input("Enter employee name: ")

conn = sqlite3.connect("helpdesk.db")

query = """
SELECT *
FROM tickets
WHERE employee_name LIKE ?
"""

result = pd.read_sql_query(
    query,
    conn,
    params=('%' + employee + '%',)
)

conn.close()

result

Enter employee name: Eric

,ticket_id,employee_name,department,issue_type,issue_description,priority,status,created_date
0,1,Eric Rathod,IT,Login Issue,Unable to login to Outlook account,High,Open,2026-06-04

Update Ticket Status

In [7]:
import sqlite3

ticket_id = int(input("Enter Ticket ID to update: "))
new_status = input("Enter new status (Open / In Progress / Closed): ")

conn = sqlite3.connect("helpdesk.db")
cursor = conn.cursor()

cursor.execute("""
UPDATE tickets
SET status = ?
WHERE ticket_id = ?
""", (new_status, ticket_id))

conn.commit()
conn.close()

print("Ticket Status Updated Successfully")

Enter Ticket ID to update: 1
Enter new status (Open / In Progress / Closed): closed
Ticket Status Updated Successfully

Delete Ticket

In [8]:
import sqlite3

ticket_id = int(input("Enter Ticket ID to delete: "))

conn = sqlite3.connect("helpdesk.db")
cursor = conn.cursor()

cursor.execute("""
DELETE FROM tickets
WHERE ticket_id = ?
""", (ticket_id,))

conn.commit()
conn.close()

print("Ticket Deleted Successfully")

Enter Ticket ID to delete: 5
Ticket Deleted Successfully

Ticket Status Report

In [9]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("helpdesk.db")

query = """
SELECT
status,
COUNT(*) AS total_tickets
FROM tickets
GROUP BY status
"""

status_report = pd.read_sql_query(query, conn)

conn.close()

status_report

        status  total_tickets
0       Closed              1
1  In Progress              1
2         Open              1
3       closed              1

Priority Report

In [10]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("helpdesk.db")

query = """
SELECT
priority,
COUNT(*) AS total_tickets
FROM tickets
GROUP BY priority
"""

priority_report = pd.read_sql_query(query, conn)

conn.close()

priority_report

  priority  total_tickets
0     High              2
1      Low              1
2   Medium              1